### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by abdelp** [thankgodr/Embedding-Images-and-Video#2]
- use just one branch onto which you create commits to respective features.
- consider using external CSS of the inline CSS in 25 in the index.html file.
- alignment of the header's logo.
- make the html markup validation.

**Comment by thankgodr** [comment]
Thank you @abdelp for these observations.

- The use of one branch was one for learning purposes, but not according to git-flow. The TSE can assume the one branch as my last branch which was pulled into master(Pull Request).

- Fixed

- Fixed

- Done
